# Python CircleCI 2.1 configuration file
version: 2.1
orbs:
    codecov: codecov/codecov@1.0.4
jobs:
    build:
        docker:
            - image: circleci/python:2.7.15
        working_directory: ~/repo
        environment:
            CODECOV_TOKEN: "6b3a45ed-be8f-48e8-b541-2ef6966220ad"
        steps:
            - checkout
            - run:
                name: install dependencies
                command: pip install --user -r requirements.txt --quiet

            - run:
                name: run tests
                command: |
                    source setup.sh
                    python -m pytest --cov-report=xml --cov=zinv tests/
            - codecov/upload:
                file: coverage.xml
